
--Desafio aula 2
DECLARE @CLIENTE VARCHAR(10);
DECLARE @IDADE INT;
DECLARE @DATANASCIMENTO DATE;
DECLARE @CUSTO FLOAT;


SET @CLIENTE = 'João';
SET @IDADE = 10;
SET @DATANASCIMENTO = '2007-01-10';
SET @CUSTO = 10.23;

PRINT @Cliente
PRINT @Idade
PRINT @DataNascimento
PRINT @Custo

-- desafio aula 3
--
DECLARE @NUMNOTAS INT;

SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = '2017-01-01';

PRINT @NUMNOTAS;

--

DECLARE @CPF VARCHAR(15);
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE INT;

SET @CPF = '1471156710';

SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());

PRINT @IDADE;