
-- Declarando novas variaveis

DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

-- Atribuindo valores as variaveis

SET @CPF = '19290992743';

SELECT * FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;


SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE 
FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;


PRINT @NOME;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;


-- Usando funções no comando PRINT

--SELECT NOME, CHARINDEX(' ', NOME), SUBSTRING(NOME, 1, CHARINDEX(' ', NOME) - 1) FROM [TABELA DE CLIENTES];

PRINT 'O primeiro nome do cliente ' + @NOME + ', cujo CPF é ' + @CPF + ', corresponde a ' + SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME) - 1)

