
-- -- Atualizando dados de uma tabela apartir de uma tabela de 
-- outro banco de dados utilizando comando merge

UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;


MERGE INTO PRODUTOS A 
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO 
WHEN MATCHED THEN 
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;


MERGE INTO CLIENTES C
USING VENDEDORES V
ON C.BAIRRO = V.BAIRRO
WHEN MATCHED THEN 
UPDATE SET C.VOLUME_COMPRA = C.VOLUME_COMPRA * 1.30;