
-- Alterar informações de uma tabela

UPDATE PRODUTOS 
SET PRECO_LISTA = 5
WHERE CODIGO = '1040107';

SELECT * FROM PRODUTOS;


UPDATE PRODUTOS
SET PRECO_LISTA = PRECO_LISTA * 1.10
WHERE SABOR = 'Manga';

SELECT * FROM PRODUTOS WHERE SABOR = 'Manga';

-- Alterando dois campos juntos


SELECT DESCRITOR FROM PRODUTOS WHERE TAMANHO = '350 ML';


SELECT DESCRITOR, REPLACE (DESCRITOR, '350 ml', '550 ml')  FROM PRODUTOS WHERE TAMANHO = '350 ML';


UPDATE PRODUTOS SET 
    DESCRITOR = replace(DESCRITOR, '350 ml', '550 ml'), 
    TAMANHO = '550 ml' WHERE TAMANHO = '350 ml';


SELECT DESCRITOR, TAMANHO, EMBALAGEM FROM PRODUTOS 
WHERE TAMANHO = '550 ml';