


CREATE TABLE TAB_IDENTITY
(ID INT IDENTITY(1,1) NOT NULL,
DESCRITOR VARCHAR(20) NULL);

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES('CLIENTE_X');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES('CLIENTE_Y');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES('CLIENTE_Z');

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES('CLIENTE_W');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES('CLIENTE_A');


DELETE FROM TAB_IDENTITY WHERE ID = 1;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES('CLIENTE_B');



CREATE TABLE TAB_IDENTITY_2
(ID INT IDENTITY(100,5) NOT NULL,
DESCRITOR VARCHAR(20) NULL);


SELECT * FROM TAB_IDENTITY_2;

INSERT INTO TAB_IDENTITY_2 (DESCRITOR) VALUES('CLIENTE_X');
INSERT INTO TAB_IDENTITY_2 (DESCRITOR) VALUES('CLIENTE_Y');
INSERT INTO TAB_IDENTITY_2 (DESCRITOR) VALUES('CLIENTE_Z');