

SELECT GETDATE();


SELECT DATENAME(WEEKDAY,GETDATE());

SELECT GETDATE(), DATEADD(DAY,5, GETDATE());

SELECT DATENAME(WEEKDAY, DATEADD(DAY, 5, GETDATE()));


DECLARE @DIA_SEMANA VARCHAR(20);
DECLARE @NUMERO_DIAS INT;

SET @NUMERO_DIAS = 16;
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()));
PRINT @DIA_SEMANA;


IF @DIA_SEMANA = 'Domingo ' OR @DIA_SEMANA = 'Sábado'
    PRINT 'Este dia é fim de semana';
ELSE
    PRINT 'Este dia é dia de semana';