SELECT * from [PRODUTOS] WHERE SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

DELETE FROM PRODUTOS WHERE CODIGO = '1001000';

SELECT * FROM [PRODUTOS] WHERE 
    SUBSTRING([DESCRITOR], 1, 15) = 'Sabor dos Alpes' 
    AND TAMANHO = '1 Litro';


DELETE FROM PRODUTOS WHERE 
    SUBSTRING([DESCRITOR], 1, 15) = 'Sabor dos Alpes' 
    AND TAMANHO = '1 Litro';


SELECT COUNT(*) FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS; 

SELECT COUNT(*) FROM PRODUTOS;


SELECT * FROM PRODUTOS 
WHERE CODIGO NOT IN (
    SELECT CODIGO_DO_PRODUTO 
    FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
);

DELETE FROM PRODUTOS 
WHERE CODIGO NOT IN (
    SELECT CODIGO_DO_PRODUTO 
    FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
);

-- Desafio: excluindo notas

DELETE N  FROM NOTAS N
INNER JOIN CLIENTES C
ON C.CPF = N.CPF
WHERE C.IDADE < 18;