

SELECT [CPF], [IDADE], [DATA_NASCIMENTO], 
    DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE()) AS IDADE
FROM CLIENTES;

SELECT CPF, NOME, IDADE FROM [CLIENTES] WHERE CPF = '1471156710';

UPDATE CLIENTES SET IDADE = DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE())
WHERE CPF = '1471156710';

CREATE TRIGGER TG_CLIENTES_IDADE
ON [dbo].[CLIENTES]
AFTER INSERT, UPDATE, DELETE
AS BEGIN
UPDATE CLIENTES SET IDADE = DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE());
END;
