
-- Selecionando uma tabela de outro banco de dados
SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;


-- Selecionando os dados a serem exportados para coincindir com a tabela destino

SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, 
    SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA 
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

-- Inserindo os dados na tabela destino

INSERT INTO PRODUTOS 
    SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, 
    SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA 
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS 
WHERE CODIGO_DO_PRODUTO <> '1040107';


SELECT * FROM PRODUTOS;

-- Importando os dados de outra base de dados

INSERT INTO CLIENTES SELECT CPF,NOME,ENDERECO_1 ASENDERECO, BAIRRO, CIDADE,ESTADO,CEP,DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,IDADE,
GENERO,LIMITE_DE_CREDITO AS LIMITE_CREDITO,VOLUME_DE_COMPRA AS VOLUME_COMPRA,PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES
WHERE CPF NOT IN ( '1471156710', '19290992743','2600586709');


SELECT * FROM CLIENTES;




