

DECLARE @LIMITE_MINIMO INT;
DECLARE @LIMITE_MAXIMO INT;
DECLARE @NUM_LINHAS_MAX INT;
DECLARE @NUM_LINHAS_ESCRITAS INT;


SET @LIMITE_MINIMO = 3;
SET @LIMITE_MAXIMO = 30;
SET @NUM_LINHAS_MAX = 10;
SET @NUM_LINHAS_ESCRITAS = 0;

PRINT 'ENTREI NO LOOPING';
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	PRINT @LIMITE_MINIMO
	SET @NUM_LINHAS_ESCRITAS = @NUM_LINHAS_ESCRITAS +1;
	IF @NUM_LINHAS_ESCRITAS = @NUM_LINHAS_MAX
	BEGIN 
	PRINT 'SAI DO LOOPING POR CAUSA DO BREAK';
	BREAK;
	END;
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1;
END;
