
-- Declaração de variáveis:

 -- 1ºopção

--DECLARE @MATRICULA VARCHAR(5); 
--DECLARE @NOME VARCHAR(100);
--DECLARE @PERCENTUAL FLOAT;
--DECLARE @DATA DATE;
--DECLARE @FERIAS BIT;
--DECLARE @BAIRRO VARCHAR(50); 

 -- 2ºopção

DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(50); 


-- Atribuindo valores as variaveis

SET @MATRICULA = '00240';
SET @NOME = 'Cláudia Rodrigues';
SET @PERCENTUAL = 0.10;
SET @DATA = '2012-03-12';
SET @FERIAS = 1;
SET @BAIRRO = 'Jardins';

-- Imprimindo os valores das variáveis

PRINT @MATRICULA;
PRINT @NOME;
PRINT @PERCENTUAL;
PRINT @DATA;
PRINT @FERIAS;
PRINT @BAIRRO;

--  Usando a variável em um comando SQL

INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES
(@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)


PRINT'UM VENDEDOR INCLUIDO'


SET @MATRICULA = '00244';
SET @NOME = 'Roberto Araujo';

INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES
(@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)

PRINT'UM VENDEDOR INCLUIDO'



SELECT * FROM [TABELA DE VENDEDORES];