

CREATE TABLE TAB_FATURAMENTO (
    DATA_VENDA DATE NULL, 
    TOTAL_VENDA FLOAT
);


SELECT 
TV.DATA_VENDA, SUM( TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;


INSERT INTO TABELA_DE_VENDAS 
VALUES ('0101', '2018-05-15', '1471156710', '235', 0.18);

INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES ('0101', '1000889', '100', 10);


INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA, SUM( TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;


SELECT * FROM TAB_FATURAMENTO;


-- ###############################################

INSERT INTO TABELA_DE_VENDAS 
VALUES ('0103', '2018-05-16', '1471156710', '235', 0.18);
INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES ('0103', '1000889', '100', 10);

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA, SUM( TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;



-- ############################################

CREATE TRIGGER TG_ITENS_VENDIDOS
ON [dbo].[TABELA_DE_ITENS_VENDIDOS]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA, SUM( TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

END;


INSERT INTO TABELA_DE_VENDAS 
VALUES ('0104', '2018-05-16', '1471156710', '235', 0.18);
INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES ('0104', '1000889', 150, 10);